<a href="https://colab.research.google.com/github/deoreshree/task14python/blob/main/task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''Q1. (Array Properties)
Create a 2D array of shape (5, 6) filled with random integers between 10 and 100.
Print the following:
Shape of the array
Total number of elements (size)
Data type (dtype)'''

import numpy as np

# Create a 2D array of shape (5, 6) with random integers between 10 and 100
arr = np.random.randint(10, 101, (5, 6))

# Print the array
print("2D Array:")
print(arr)

# Print array properties
print("\nShape of the array:", arr.shape)
print("Total number of elements (size):", arr.size)
print("Data type (dtype):", arr.dtype)


2D Array:
[[78 40 85 25 91 91]
 [22 31 75 17 12 13]
 [47 84 87 66 26 73]
 [88 53 74 45 76 12]
 [98 98 97 90 86 11]]

Shape of the array: (5, 6)
Total number of elements (size): 30
Data type (dtype): int64


In [1]:

'''Q2. (Statistical Methods - Basic)
Generate a 1D array of 20 random numbers between 1 and 50 using
np.random.randint().
Print:
Minimum value and its index (argmin)
Maximum value and its index (argmax)
Sum of all elements
Mean and Standard Deviation'''

import numpy as np

# Generate a 1D array of 20 random numbers between 1 and 50
arr = np.random.randint(1, 51, 20)

# Print the array
print("Generated Array:")
print(arr)

# Minimum value and its index
print("\nMinimum Value:", np.min(arr))
print("Index of Minimum Value:", np.argmin(arr))

# Maximum value and its index
print("\nMaximum Value:", np.max(arr))
print("Index of Maximum Value:", np.argmax(arr))

# Sum of all elements
print("\nSum of All Elements:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))



Generated Array:
[24 25 30 38 11 13 32 39 28 31 32 31 35 20 20 14 34  1 18 28]

Minimum Value: 1
Index of Minimum Value: 17

Maximum Value: 39
Index of Maximum Value: 7

Sum of All Elements: 504
Mean: 25.2
Standard Deviation: 9.734474818910366


In [2]:
import numpy as np

# Create a 4x5 matrix of random integers between 20 and 80
matrix = np.random.randint(20, 81, (4, 5))

# Print the matrix
print("Generated 4x5 Matrix:")
print(matrix)

# Minimum and Maximum value
print("\nMinimum Value:", np.min(matrix))
print("Maximum Value:", np.max(matrix))

# Sum of all elements
print("\nSum of All Elements:", np.sum(matrix))

# Mean
print("Mean:", np.mean(matrix))

# Standard Deviation
print("Standard Deviation:", np.std(matrix))

# Sum of each row
print("\nSum of Each Row:")
print(np.sum(matrix, axis=1))

# Sum of each column
print("\nSum of Each Column:")
print(np.sum(matrix, axis=0))

Generated 4x5 Matrix:
[[45 43 68 77 24]
 [62 67 41 50 62]
 [29 40 60 53 23]
 [40 75 57 74 52]]

Minimum Value: 23
Maximum Value: 77

Sum of All Elements: 1042
Mean: 52.1
Standard Deviation: 15.977797094718658

Sum of Each Row:
[257 282 205 298]

Sum of Each Column:
[176 225 226 254 161]


In [3]:
import numpy as np

# Create a 1D array containing numbers from 1 to 24
arr = np.arange(1, 25)

# Print the original array
print("Original 1D Array:")
print(arr)
print("Shape:", arr.shape)

# Reshape into (4, 6)
arr1 = arr.reshape(4, 6)
print("\nReshaped Array (4, 6):")
print(arr1)
print("Shape:", arr1.shape)

# Reshape into (3, 8)
arr2 = arr.reshape(3, 8)
print("\nReshaped Array (3, 8):")
print(arr2)
print("Shape:", arr2.shape)

# Reshape into (2, 3, 4)
arr3 = arr.reshape(2, 3, 4)
print("\nReshaped Array (2, 3, 4):")
print(arr3)
print("Shape:", arr3.shape)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshaped Array (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshaped Array (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshaped Array (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [4]:
import numpy as np

# Create the array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

# Print the original array
print("Original Array:")
print(arr)

# Extract first row
print("\nFirst Row:")
print(arr[0])

# Extract last column
print("\nLast Column:")
print(arr[:, -1])

# Extract center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

# Extract all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [5]:
import numpy as np

# Create a 5x5 matrix of random integers between 1 and 100
arr = np.random.randint(1, 101, (5, 5))

# Print the original matrix
print("Original Matrix:")
print(arr)

# Print diagonal elements
print("\nDiagonal Elements:")
print(np.diag(arr))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace all elements less than 30 with 0
arr[arr < 30] = 0

# Print the modified array
print("\nModified Matrix (Elements < 30 replaced with 0):")
print(arr)

Original Matrix:
[[  1  83  49  99  52]
 [ 32  75  57  74  16]
 [ 15   8  59  32  44]
 [ 75  23  49  34  90]
 [ 93 100   9  35  94]]

Diagonal Elements:
[ 1 75 59 34 94]

Elements Greater Than 50:
[ 83  99  52  75  57  74  59  75  90  93 100  94]

Modified Matrix (Elements < 30 replaced with 0):
[[  0  83  49  99  52]
 [ 32  75  57  74   0]
 [  0   0  59  32  44]
 [ 75   0  49  34  90]
 [ 93 100   0  35  94]]


In [6]:
import numpy as np
# Create two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
# Print the arrays
print("Array a:", a)
print("Array b:", b)

# Addition
print("\nAddition:")
print(a + b)
# Subtraction
print("\nSubtraction:")
print(a - b)
# Multiplication
print("\nMultiplication:")
print(a * b)
# Division
print("\nDivision:")
print(a / b)
# Element-wise Power
print("\nElement-wise Power (a ** b):")
print(a ** b)
# Modulo Operation
print("\nModulo Operation (a % b):")
print(a % b)

Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power (a ** b):
[     10     400   27000 2560000]

Modulo Operation (a % b):
[0 0 0 0]


In [7]:
import numpy as np
# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Print the matrices
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication
elementwise = A * B
print("\nElement-wise Multiplication (A * B):")
print(elementwise)

# Matrix multiplication
matrix_mult = A @ B      # You can also use np.dot(A, B)
print("\nMatrix Multiplication (A @ B):")
print(matrix_mult)

# Difference:
# A * B performs multiplication of corresponding elements.
# A @ B (or np.dot(A, B)) performs matrix multiplication
# by multiplying rows of A with columns of B.


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [8]:
# Q9. (Combined - Properties + Operations + Indexing)

import numpy as np

# Generate a 6x6 matrix of random numbers
matrix = np.random.randn(6, 6)

# Print the original matrix
print("Original Matrix:\n", matrix)

# Print shape, size, and data type
print("\nShape:", matrix.shape)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

# Find index of maximum and minimum value
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
min_index = np.unravel_index(np.argmin(matrix), matrix.shape)

print("\nMaximum Value:", matrix[max_index])
print("Index of Maximum Value:", max_index)

print("\nMinimum Value:", matrix[min_index])
print("Index of Minimum Value:", min_index)

# Extract the top-left 3x3 submatrix
submatrix = matrix[:3, :3]
print("\nTop-Left 3x3 Submatrix:\n", submatrix)

# Replace all negative numbers with their absolute value
modified_matrix = np.abs(matrix)

print("\nModified Matrix (Negative values replaced with absolute values):\n")
print(modified_matrix)

# Print the mean of the modified matrix
print("\nMean of Modified Matrix:", np.mean(modified_matrix))

Original Matrix:
 [[ 0.63655598  2.65328829 -0.03048305 -0.15431344  1.68969509 -0.86180754]
 [ 0.34190302 -1.50649218 -0.56120003  1.30636474  1.06645987 -2.51821699]
 [-0.82084758 -0.17031153 -0.82052663 -0.42427573  0.10231915  0.21928645]
 [-1.91781581  0.28895769  1.46654302  0.46290552  1.0255668   1.18577837]
 [ 0.84485522  0.10375411 -0.20254538 -0.31668705  0.78348973 -0.58467724]
 [ 0.85030256 -0.9645362  -2.27445488 -0.31364353 -1.62759425  0.75620629]]

Shape: (6, 6)
Size: 36
Data Type: float64

Maximum Value: 2.65328828656145
Index of Maximum Value: (np.int64(0), np.int64(1))

Minimum Value: -2.5182169898659725
Index of Minimum Value: (np.int64(1), np.int64(5))

Top-Left 3x3 Submatrix:
 [[ 0.63655598  2.65328829 -0.03048305]
 [ 0.34190302 -1.50649218 -0.56120003]
 [-0.82084758 -0.17031153 -0.82052663]]

Modified Matrix (Negative values replaced with absolute values):

[[0.63655598 2.65328829 0.03048305 0.15431344 1.68969509 0.86180754]
 [0.34190302 1.50649218 0.56120003 1.

In [9]:
# Q10. (Mini Project - Student Performance Analysis)

import numpy as np

# ----------------------------------------------------
# Generate a 2D array (10 students × 5 subjects)
# Random marks between 30 and 100
# ----------------------------------------------------
marks = np.random.randint(30, 101, size=(10, 5))

# Print the marks array
print("Student Marks (10 Students × 5 Subjects):")
print(marks)

# ----------------------------------------------------
# Calculate total marks and average for each student
# ----------------------------------------------------
total_marks = np.sum(marks, axis=1)      # Sum of each row
average_marks = np.mean(marks, axis=1)   # Average of each row

print("\nTotal Marks of Each Student:")
print(total_marks)

print("\nAverage Marks of Each Student:")
print(average_marks)

# ----------------------------------------------------
# Find student with highest and lowest total marks
# ----------------------------------------------------
highest_student = np.argmax(total_marks)
lowest_student = np.argmin(total_marks)

print("\nStudent with Highest Total Marks:")
print("Student Index:", highest_student)
print("Total Marks:", total_marks[highest_student])

print("\nStudent with Lowest Total Marks:")
print("Student Index:", lowest_student)
print("Total Marks:", total_marks[lowest_student])

# ----------------------------------------------------
# Calculate overall class statistics
# ----------------------------------------------------
class_mean = np.mean(marks)
class_std = np.std(marks)

print("\nOverall Class Mean:", class_mean)
print("Overall Class Standard Deviation:", class_std)

# ----------------------------------------------------
# Sort students based on total marks (highest first)
# ----------------------------------------------------
sorted_indices = np.argsort(total_marks)[::-1]

print("\nRanking of Students (Highest to Lowest):")
print(sorted_indices)

# ----------------------------------------------------
# Extract marks of Top 3 students using indexing
# ----------------------------------------------------
top3_students = marks[sorted_indices[:3]]

print("\nMarks of Top 3 Students:")
print(top3_students)

# ----------------------------------------------------
# Reshape the array (Example: 10x5 → 5x10)
# ----------------------------------------------------
reshaped_marks = marks.reshape(5, 10)

print("\nReshaped Array (5 × 10):")
print(reshaped_marks)

# ----------------------------------------------------
# Demonstrate indexing
# ----------------------------------------------------
print("\nMarks of First Student:")
print(marks[0])

print("\nMarks of First Subject for All Students:")
print(marks[:, 0])

print("\nMarks of Top Student:")
print(marks[highest_student])

print("\nProgram Completed Successfully!")

Student Marks (10 Students × 5 Subjects):
[[ 66  54  95  68  91]
 [ 81  63  76  58  58]
 [ 93  58  77  99  97]
 [ 39  30  53  90  71]
 [ 39  44  79  85  77]
 [ 78  65  31  89  79]
 [ 58  35  35  58  97]
 [ 68  81  73  44  50]
 [ 30  99  86 100  97]
 [ 32  95  62  78  45]]

Total Marks of Each Student:
[374 336 424 283 324 342 283 316 412 312]

Average Marks of Each Student:
[74.8 67.2 84.8 56.6 64.8 68.4 56.6 63.2 82.4 62.4]

Student with Highest Total Marks:
Student Index: 2
Total Marks: 424

Student with Lowest Total Marks:
Student Index: 3
Total Marks: 283

Overall Class Mean: 68.12
Overall Class Standard Deviation: 21.480819351225875

Ranking of Students (Highest to Lowest):
[2 8 0 5 1 4 7 9 6 3]

Marks of Top 3 Students:
[[ 93  58  77  99  97]
 [ 30  99  86 100  97]
 [ 66  54  95  68  91]]

Reshaped Array (5 × 10):
[[ 66  54  95  68  91  81  63  76  58  58]
 [ 93  58  77  99  97  39  30  53  90  71]
 [ 39  44  79  85  77  78  65  31  89  79]
 [ 58  35  35  58  97  68  81  73  44  